version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index

  app:
    build:
      context: .
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - CHROMA_URL=http://chromadb:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - chromadb
    volumes:
      - ./knowledge:/app/knowledge

volumes:
  chroma_data: 